export interface Person {
  givenName: string;
  surName: string;
  age: number;
  email: string;
  address: string;
}

export interface EPerson {
  givenName: string;
  surName: string;
  age: string;
  email: string;
  education: string;
}

export const ManyPerson: EPerson[] = [
  {
    givenName: 'Dylan',
    surName: 'Davis',
    age: '46',
    email: 'dmdavis@ymail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Ryan',
    surName: 'Young',
    age: '32',
    email: 'ryoung@live.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Charlotte',
    surName: 'Barnes',
    age: '44',
    email: 'charlotte_barnes@ymail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'David',
    surName: 'Watson',
    age: '41',
    email: 'd_w_watson@hotmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Erin',
    surName: 'Peterson',
    age: '53',
    email: 'e.m78@yahoo.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Rebecca',
    surName: 'Young',
    age: '55',
    email: 'rebeccayoung@outlook.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Robert',
    surName: 'Ward',
    age: '71',
    email: 'r_ward57@ymail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Theodore',
    surName: 'White',
    age: '75',
    email: 't_a_white@gmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Lauren',
    surName: 'Turner',
    age: '31',
    email: 'laurenleeturner@aol.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Isabella',
    surName: 'Parker',
    age: '21',
    email: 'isabellaanneparker@outlook.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Nicholas',
    surName: 'Harris',
    age: '39',
    email: 'nharris@aol.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Emma',
    surName: 'Parker',
    age: '25',
    email: 'eparker8@aol.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Lauren',
    surName: 'Nelson',
    age: '46',
    email: 'laurendnelson@gmail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Anna',
    surName: 'Campbell',
    age: '45',
    email: 'anna.campbell@live.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Gabriel',
    surName: 'Parker',
    age: '51',
    email: 'gabriel.joseph.parker@aol.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Henry',
    surName: 'Long',
    age: '70',
    email: 'henry_alan_long@yahoo.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Jose',
    surName: 'Jones',
    age: '59',
    email: 'j.jones@rocketmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Andrew',
    surName: 'Williams',
    age: '72',
    email: 'a.a@hotmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Joshua',
    surName: 'Thomas',
    age: '25',
    email: 'joshua_a_thomas@live.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Chelsea',
    surName: 'White',
    age: '25',
    email: 'chelsea_rose_white@hotmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Heather',
    surName: 'Clark',
    age: '44',
    email: 'hmclark@hotmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Joshua',
    surName: 'Nelson',
    age: '21',
    email: 'joshua.nelson@outlook.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Kelsey',
    surName: 'Perry',
    age: '20',
    email: 'kelseygraceperry@aol.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Sara',
    surName: 'Simmons',
    age: '43',
    email: 'sara.anne.simmons@aol.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Mary',
    surName: 'Griffin',
    age: '65',
    email: 'm_k_griffin@rocketmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'David',
    surName: 'Washington',
    age: '35',
    email: 'davidwashington57@rocketmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Daniel',
    surName: 'Taylor',
    age: '22',
    email: 'daniel.taylor@live.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Sebastian',
    surName: 'Mitchell',
    age: '68',
    email: 'samitchell@yahoo.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Joseph',
    surName: 'Sanders',
    age: '30',
    email: 'j_c_sanders@aol.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Sarah',
    surName: 'Richardson',
    age: '30',
    email: 's_richardson88@outlook.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Joseph',
    surName: 'Stewart',
    age: '34',
    email: 'josephstewart@rocketmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Alexis',
    surName: 'James',
    age: '69',
    email: 'alexisgjames@live.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Brianna',
    surName: 'Ramirez',
    age: '55',
    email: 'b_ramirez@rocketmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Victoria',
    surName: 'Hernandez',
    age: '67',
    email: 'victoria.r.hernandez@aol.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Richard',
    surName: 'Richardson',
    age: '33',
    email: 'r.a.richardson@gmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'John',
    surName: 'Clark',
    age: '69',
    email: 'j_j_clark@ymail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Brian',
    surName: 'Baker',
    age: '51',
    email: 'briancbaker@yahoo.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Heather',
    surName: 'Roberts',
    age: '52',
    email: 'heather_roberts@outlook.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Owen',
    surName: 'Garcia',
    age: '77',
    email: 'o_h_garcia81@outlook.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Katherine',
    surName: 'Russell',
    age: '49',
    email: 'katherine_russell@yahoo.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Andrew',
    surName: 'Green',
    age: '25',
    email: 'andrew_green@gmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Victoria',
    surName: 'Collins',
    age: '60',
    email: 'vgcollins@hotmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Amelia',
    surName: 'Butler',
    age: '59',
    email: 'a.butler67@ymail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Joshua',
    surName: 'James',
    age: '60',
    email: 'jjames@ymail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Brian',
    surName: 'Wright',
    age: '36',
    email: 'brian.scott.wright@gmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Daniel',
    surName: 'Perez',
    age: '64',
    email: 'danielsperez@hotmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Mateo',
    surName: 'Reed',
    age: '19',
    email: 'm_reed@ymail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Julian',
    surName: 'Green',
    age: '18',
    email: 'j.a.green@gmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Kelsey',
    surName: 'Turner',
    age: '65',
    email: 'kelsey.turner@hotmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Abigail',
    surName: 'Garcia',
    age: '21',
    email: 'abigail.d.garcia@gmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Brittany',
    surName: 'Flores',
    age: '55',
    email: 'brittany.s.flores@hotmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Kaitlyn',
    surName: 'Miller',
    age: '37',
    email: 'kaitlyn_marie_miller7@ymail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Sean',
    surName: 'Wood',
    age: '71',
    email: 'swood@gmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Eleanor',
    surName: 'Lewis',
    age: '68',
    email: 'eleanor16@gmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Mateo',
    surName: 'Collins',
    age: '66',
    email: 'mjcollins16@aol.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Olivia',
    surName: 'Jones',
    age: '59',
    email: 'oajones@hotmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Henry',
    surName: 'Johnson',
    age: '51',
    email: 'h.johnson38@rocketmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Aubrey',
    surName: 'Martinez',
    age: '32',
    email: 'aubrey.n.martinez@rocketmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Gabriel',
    surName: 'Bailey',
    age: '63',
    email: 'g_m_bailey@outlook.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Mark',
    surName: 'Jenkins',
    age: '35',
    email: 'mark75@gmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Katherine',
    surName: 'Clark',
    age: '58',
    email: 'k_k_clark59@rocketmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Adam',
    surName: 'Gray',
    age: '23',
    email: 'aagray@outlook.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Amelia',
    surName: 'Russell',
    age: '76',
    email: 'amelia.m@ymail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Mateo',
    surName: 'Lewis',
    age: '42',
    email: 'mateolewis26@aol.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Sebastian',
    surName: 'Taylor',
    age: '72',
    email: 'sebastian_taylor13@outlook.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Sofia',
    surName: 'Campbell',
    age: '36',
    email: 's_k_campbell10@outlook.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Thomas',
    surName: 'Peterson',
    age: '41',
    email: 'thomas@live.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Abigail',
    surName: 'Parker',
    age: '74',
    email: 'abigailrparker@yahoo.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Emma',
    surName: 'Ross',
    age: '61',
    email: 'elross21@ymail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Stephanie',
    surName: 'Martinez',
    age: '40',
    email: 'smmartinez@rocketmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Stephen',
    surName: 'Hernandez',
    age: '37',
    email: 'stephen.hernandez@live.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Samuel',
    surName: 'Rogers',
    age: '24',
    email: 's_j_rogers@hotmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Michelle',
    surName: 'Martin',
    age: '76',
    email: 'mrmartin@gmail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Eleanor',
    surName: 'Carter',
    age: '61',
    email: 'ecarter@aol.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Eleanor',
    surName: 'Ross',
    age: '48',
    email: 'eleanor.m.ross@aol.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Brittany',
    surName: 'Ross',
    age: '70',
    email: 'b.a.ross76@rocketmail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'John',
    surName: 'Allen',
    age: '53',
    email: 'j_a_allen@aol.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Oliver',
    surName: 'James',
    age: '28',
    email: 'o.w.james@outlook.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Timothy',
    surName: 'Reed',
    age: '57',
    email: 't.a.reed@ymail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Ryan',
    surName: 'Hayes',
    age: '65',
    email: 'rhayes@gmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Sophia',
    surName: 'Young',
    age: '22',
    email: 's.young@gmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Aubrey',
    surName: 'Morris',
    age: '39',
    email: 'amorris@rocketmail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Maria',
    surName: 'Long',
    age: '33',
    email: 'mflong@aol.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Amanda',
    surName: 'Bell',
    age: '38',
    email: 'amandarbell41@hotmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Jeremy',
    surName: 'Bailey',
    age: '44',
    email: 'jeremy.scott.bailey@outlook.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Thomas',
    surName: 'Foster',
    age: '70',
    email: 'tfoster@outlook.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Jennifer',
    surName: 'Green',
    age: '73',
    email: 'j.green@hotmail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Adam',
    surName: 'Jones',
    age: '42',
    email: 'adam_a_jones@outlook.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Isabella',
    surName: 'Phillips',
    age: '24',
    email: 'i_phillips@hotmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Samuel',
    surName: 'Martin',
    age: '42',
    email: 'samuel_t_martin@gmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Layla',
    surName: 'Russell',
    age: '52',
    email: 'layla_russell@ymail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'John',
    surName: 'Parker',
    age: '24',
    email: 'john_parker@live.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Haley',
    surName: 'Peterson',
    age: '60',
    email: 'haley_jean_peterson@gmail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Henry',
    surName: 'Allen',
    age: '30',
    email: 'h.allen@yahoo.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Brian',
    surName: 'Stewart',
    age: '43',
    email: 'b_stewart@live.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Megan',
    surName: 'Rodriguez',
    age: '31',
    email: 'meganrodriguez@live.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Taylor',
    surName: 'Jackson',
    age: '77',
    email: 't_l_jackson@gmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Steven',
    surName: 'Davis',
    age: '21',
    email: 'steven.michael@aol.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'John',
    surName: 'Campbell',
    age: '40',
    email: 'johncampbell@aol.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Jessica',
    surName: 'Ross',
    age: '25',
    email: 'j.l.ross@rocketmail.com',
    education: 'Doctoral degree',
  },
];
